name: Post to Facebook

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour (UTC); you can adjust timing
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  post:
    runs-on: ubuntu-latest
    env:
      FB_PAGE_ID: 226428187567462
      FB_PAGE_TOKEN: ${{ secrets.FB_PAGE_TOKEN }}
      SHEET_ID: your-google-sheet-id-here
      SHEET_TAB: Sheet1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Fetch today’s post from Google Sheet
        run: |
          node fetch-sheet.js > post.txt
          echo "POST=$(cat post.txt)" >> $GITHUB_ENV

      - name: Post to Facebook
        run: |
          curl -X POST "https://graph.facebook.com/$FB_PAGE_ID/feed" \
            -F "message=$POST" \
            -F "access_token=$FB_PAGE_TOKEN"
